# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Terraform pipeline definition
# https://www.terraform.io/docs/providers/azurerm/guides/azure_pipelines.html

trigger:
- master

pool:
  vmImage: 'Ubuntu-Latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
  displayName: 'Use Python 3.x'

- script: |
    sudo apt-get update
    sudo apt-get install -y unzip
    sudo apt-get install -y curl
    curl https://releases.hashicorp.com/terraform/0.15.7/terraform_0.15.7_linux_amd64.zip -o terraform.zip
    unzip terraform.zip
    sudo mv terraform /usr/local/bin/
    terraform -version
  displayName: 'Install Terraform'

- script: |
    terraform init
  displayName: 'Terraform Init'

- script: |
    terraform plan
  displayName: 'Terraform Plan'

- script: |
    terraform apply -auto-approve
  displayName: 'Terraform Apply'
